name: for testing
on: 
   push:
     branches:
       - "main"
   workflow_dispatch:
      inputs:
         abc: 
            description: "Enter file name"
            type: string
            required: true
            default: demo.txt
jobs:
    first_job:
       runs-on: ubuntu-latest
       continue-on-error: true
       steps:
         - name: get code
           uses: actions/checkout@v3
         - name: run dic script
           run: python3 dic.py
         - name: run list script
           run: python lis.py
           continue-on-error: true
         - name: run tuple script
           run: python3 tuple.py  
         - name: create demo file
           run: echo " This is a demo file" > ${{ github.event.inputs.abc}}
         - name: upload outpuut
           uses: actions/upload-artifact@v3
           with:
              name: myvol
              path: ${{ github.event.inputs.abc}} 
    second_job:
        # if: github.event_name == 'push'
        runs-on: ubuntu-latest
        needs: first_job
        steps:
         - name: get code
           uses: actions/checkout@v3
         - name: run tuple script
           run: python3 tuple.py
         - name: list file
           run: ls -lrt
         - name: download file
           uses: actions/download-artifact@v3
           with:
             name: myvol
         - name: read file
           run: |
              ls -lrt
              cat ${{ github.event.inputs.abc}}
